# Generated by Django 3.1.4 on 2021-01-18 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='parent_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_tasks', to='app.tasks'),
        ),
    ]
